package com.demo.mapper;

import com.demo.pojo.RoleAndFunctionExample;
import com.demo.pojo.RoleAndFunctionKey;
import java.util.List;

public interface RoleAndFunctionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_role_function
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(RoleAndFunctionKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_role_function
     *
     * @mbg.generated
     */
    int insert(RoleAndFunctionKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_role_function
     *
     * @mbg.generated
     */
    int insertSelective(RoleAndFunctionKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_role_function
     *
     * @mbg.generated
     */
    List<RoleAndFunctionKey> selectByExample(RoleAndFunctionExample example);
}