package com.demo.mapper;

import com.demo.pojo.UserAndRoleExample;
import com.demo.pojo.UserAndRoleKey;
import java.util.List;

public interface UserAndRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_role
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(UserAndRoleKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_role
     *
     * @mbg.generated
     */
    int insert(UserAndRoleKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_role
     *
     * @mbg.generated
     */
    int insertSelective(UserAndRoleKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_role
     *
     * @mbg.generated
     */
    List<UserAndRoleKey> selectByExample(UserAndRoleExample example);
}